version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  my-executor:
    docker:
      - image: "circleci/node:10.15.3"
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
        environment:
          - cluster.name: es-test-cluster
          - xpack.security.enabled: false
          - transport.host: localhost
          - network.host: 127.0.0.1
          - http.port: 9200
          - discovery.type: single-node
jobs:
  build-and-test:
    executor: my-executor
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn run test:server
workflows:
  build-and-test:
    jobs:
      - build-and-test
